In [1]:
#This is a note book of: https://www.youtube.com/watch?v=QUT1VHiLmmI&ab_channel=freeCodeCamp.org

In [4]:
import numpy as np

array([12,  3])

In [6]:
arr = [[1.0,2.0,3.0],[1,2,3]]
arr

[[1.0, 2.0, 3.0], [1, 2, 3]]

In [16]:
arr = np.array([[1.0,2.0,3.0],[1,2,3]])
#numpy accept only a single type
arr

array([[1., 2., 3.],
       [1., 2., 3.]])

In [14]:
#number of dimentions
arr = np.array([[1,2,3],[1,2,3]])
arr.ndim

2

In [18]:
#shape of array
arr.shape

(2, 3)

In [20]:
#data type of array
arr.dtype

dtype('float64')

In [21]:
arr = np.array([[1,2,3],[1,2,3]],dtype='int16')
arr.dtype

dtype('int16')

In [22]:
arr.nbytes #6*2bytes

12

In [33]:
#access elements
arr = np.array([[1,2,3,4],[11,22,33,44]],dtype='int16')
arr[1,0]

11

In [28]:
#access specific column
arr[:,1]

array([ 2, 22], dtype=int16)

In [35]:
#access start,end(up to end not including),step
arr[1, 1:5:2]

array([22, 44], dtype=int16)

In [45]:
#make array of zeros
zeros=np.zeros((10,10))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
zeros = zeros + 1
zeros

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
#make an array of same value
full_arr = np.full((2,2),4, dtype='float64') #or full_arr = np.full(arr.shape,4,dtype='float64')
full_arr

array([[4., 4.],
       [4., 4.]])

In [50]:
# to make random numbers
np.random.rand(4,2)

array([[0.79847586, 0.94642463],
       [0.04825335, 0.21539773],
       [0.45484419, 0.14400279],
       [0.24059419, 0.24227453]])

In [57]:
# rand it in a domain between 4 and 7
np.random.randint(4,7, size=(3,3))

array([[4, 4, 4],
       [6, 4, 6],
       [4, 4, 4]])

In [60]:
# to repeat the same array multiple times
row = [1,2,3]
np.repeat(row,3,axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [66]:
row = [[1,2,3]]
np.repeat(row,3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [72]:
ones = np.ones((5,5))
print(ones)

zeros = np.zeros((3,3))
print(zeros)

ones[1:4,1:4] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Math

In [75]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [76]:
arr -2

array([-1,  0,  1])

In [77]:
arr + 2

array([3, 4, 5])

In [78]:
arr / 2

array([0.5, 1. , 1.5])

In [79]:
arr * 2 

array([2, 4, 6])

In [81]:
arr / arr

array([1., 1., 1.])

In [82]:
arr ** arr

array([ 1,  4, 27])

In [88]:
#identity array 
c = np.identity(2)
c

array([[1., 0.],
       [0., 1.]])

In [70]:
np.linalg.det(arr)

LinAlgError: Last 2 dimensions of the array must be square

In [92]:
np.min(arr, axis=1)

array([1, 2, 5])

In [93]:
np.min(arr, axis=0)

array([1, 2, 3])

In [94]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [95]:
arr.reshape((1,9))

array([[1, 2, 3, 2, 3, 4, 5, 6, 7]])

In [96]:
arr.reshape((3,3))

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

# Array Insertion

In [38]:
# insert(location, value, axis)
arr = np.ones((3,3,3),dtype='int32')
arr


array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [44]:
new_arr = np.insert(arr, 0,np.array([2,2,2]), axis=1)
new_arr

array([[[2, 2, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [61]:
new_arr = np.insert(arr, 1,np.array([1,2,3]), axis=2)
print(new_arr)
print('##')
new_arr = np.insert(arr, 1,np.array(2), axis=2)
print(new_arr)

[[[1 1 1 1]
  [1 2 1 1]
  [1 3 1 1]]

 [[1 1 1 1]
  [1 2 1 1]
  [1 3 1 1]]

 [[1 1 1 1]
  [1 2 1 1]
  [1 3 1 1]]]
##


In [60]:
for plate in arr:
    for row in plate:
        for element in row:
            print(element)

In [63]:
new_arr[2,1,:] # access plate 2, row=1 and all elements in that row

array([1, 2, 1, 1], dtype=int32)

# Array deletion

In [84]:
print(new_arr)
np.delete(new_arr, [0,1], axis=1)

[[[1 1 1 1]
  [1 2 1 1]
  [1 3 1 1]]

 [[1 1 1 1]
  [1 2 1 1]
  [1 3 1 1]]

 [[1 1 1 1]
  [1 2 1 1]
  [1 3 1 1]]]


array([[[1, 3, 1, 1]],

       [[1, 3, 1, 1]],

       [[1, 3, 1, 1]]], dtype=int32)

# Array append

In [105]:
arr = np.array([[1,2,3,4]])
np.append(arr,[[1,2,3,4]], axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [109]:
#concatenate array
np.concatenate((arr, arr, arr), axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

# split

In [118]:
np.split(np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]),2, axis=1)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]])]

In [119]:
#np.concatenate(np.split(np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]),2, axis=1))

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])